project:
  output-dir: output
  render:
    - "*.qmd"
    - "!assets/"
#format:
#  html:
#    css: styles.css
#    html-math-method: katex
#  pdf:
#    documentclass: report
#    margin-left: 30mm
#    margin-right: 30mm
