---
title: "CV"
name: Jon
surname: Reades
position: "Associate Professor"
address: |
         | Centre for Advanced Spatial Analysis
         | University College London (UCL)
         | London, U.K.
phone: "+44 797 698 7392"
www: https://www.ucl.ac.uk/bartlett/casa/people/dr-jonathan-reades
email: "j.reades@ucl.ac.uk"
orcid: 0000-0002-1443-9263
github: jreades
publons: 2897251
#researchgate: 7004827878
googlescholar: jreades
#date: "`r format(Sys.time(), '%B %Y')`"
date: today
date-format: "D MMMM YYYY"
output: 
  vitae::awesomecv:
    page_total: true
    extra_dependencies: ["flafter"]
---

# Publications 

```{python load-bib, python.reticulate=FALSE}
#| echo: false
import os
from quikbib import load_bib, filter_bib 
from quiksort import sort_records

#my_pubs = filter_bib(load_bib(os.path.join('assets','pubs.bib')), 
#                    {'year':'<2017', 'priority':'<2'}, {'priority':'1', 'foo':'baz'})

my_pubs = filter_bib(load_bib(os.path.join('assets','pubs.bib')), {}, {'priority':'1', 'foo':'baz'})

for p in sort_records(my_pubs, '-year'):
  print(f"{p['title'][:25]}: {p['ENTRYTYPE']}, {p['priority']}, {p['year']}, {p['foo']}")
```

# About me

 * My undergraduate degree was in Comparative Literature, but I graduated in the (first) dot.com boom and learned coding-by-doing.
 * My areas of interest include neighbourhoods, .

# Education

```{python education-details, python.reticulate=FALSE}
#| echo: false
import os
from quikcsv import load_csv, filter_csv
from quiksort import sort_records

edf = filter_csv(load_csv(os.path.join('assets','education.csv')), {}, {'foo':'bar'})
for v in sort_records(edf, '-Year'):
  print(f"{v['Institution']}, {v['Year']}, {v['foo']}")
```

```{r knitr-setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE,
                      fig.show='asis', 
                      out.width="0.6\\linewidth", 
                      fig.align='center')
```

```{r current-year}
# Retrieve current year
current_year <- as.numeric(as.character(Sys.time(), '%Y')) # Update year
```